server:
  port: 8090
  forward-headers-strategy: framework
spring:
  application:
    name: kexit-core
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 457981249259-r43o962jlge9mjlnb7ph3b41ruv3n8mj.apps.googleusercontent.com
            client-secret: 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
            scope:
              - openid
              - email
              - profile
              - https://www.googleapis.com/auth/drive.readonly
        provider:
          google:
            authorizationUri: https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&prompt=select_account
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/kexit-drive?authSource=admin
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: password
    listener:
      direct:
        retry:
          enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKAHOSTNAME:localhost}:8761/eureka/
  instance:
    healthCheckUrlPath: /actuator/health
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

google-apis-url: https://www.googleapis.com
mime-types-to-export:
  mapping:
    "[application/vnd.google-apps.document]":
      "extension": "docx"
      "export-mime-type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    "[application/vnd.google-apps.spreadsheet]":
      extension: "xlsx"
      export-mime-type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    "[application/vnd.google-apps.presentation]":
      extension: "pptx"
      export-mime-type: "application/vnd.openxmlformats-officedocument.presentationml.presentation"
    "[application/vnd.google-apps.drawing]":
      extension: "png"
      export-mime-type: "image/png"
    "[application/vnd.google-apps.script]":
      extension: "json"
      export-mime-type: "application/vnd.google-apps.script+json"
